BugTracker/Models/Bug.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Models
{
    public class Bug
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        //public Status Status { get; set; }
        public string Description { get; set; }
    }
    //public class Status
    //{
    //    public int Id { get; set; }
    //    public string Name { get; set; }

    //    public List<Bug> Bugs { get; set; }
    //    public Status()
    //    {
    //        Bugs = new List<Bug>();
    //    }
    //}
    
    
}

BugTracker/Models/BugsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BugTracker.Models
{
    public class BugsContext : DbContext
    {
        public DbSet<Bug> Bugs { get; set; }
        public DbSet<Improvement> Improvements { get; set; }
        public DbSet<Status> Statuses {get; set;}
        public BugsContext(DbContextOptions<BugsContext> options)
            : base(options)
        {
            Database.EnsureCreated();   
        }
    }
}

BugTracker/Models/ErrorViewModel.cs
using System;

namespace BugTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BugTracker/Models/Improvement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Models
{
    public class Improvement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CurrentStatus { get; set; }
        public List<Status> Statuses { get; set; }
        public Improvement() 
        {
            Statuses = new List<Status>();
            //CurrentStatus = Statuses.ToArray()[0].Name;
        }
    }
    public class Status
    { 
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Improvement> Improvements { get; set; }
        public Status()
        {
            Improvements = new List<Improvement>();
        }
    }
}

BugTracker/ViewModels/IndexViewModel.cs
using BugTracker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.ViewModels
{
    public class IndexViewModel
    {
        public IEnumerable<Improvement> Improvements { get; set; }
        public IEnumerable<Status> Statuses { get; set; }
    }
}

BugTracker/Controllers/HomeController.cs
using BugTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Controllers
{
    public class HomeController : Controller
    {

        private BugsContext db;
        public HomeController(BugsContext context)
        {
            db = context;
        }
        
        public async Task<IActionResult> Index()
        {
            return View(await db.Bugs.ToListAsync());
        }
        public IActionResult Create()
        {         
           
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(Bug bug)
        {
            db.Bugs.Add(bug);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Bug bug = await db.Bugs.FirstOrDefaultAsync(p => p.Id == id);
                if (bug != null)
                    return View(bug);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Bug bug)
        {
            db.Bugs.Update(bug);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Bug bug = await db.Bugs.FirstOrDefaultAsync(b => b.Id == id);
                if (bug != null)
                    return View(bug);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Bug bug = await db.Bugs.FirstOrDefaultAsync(b => b.Id == id);
                if (bug != null)
                {
                    db.Bugs.Remove(bug);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BugTracker/Controllers/SolveController.cs
using BugTracker.Models;
using BugTracker.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BugTracker.Controllers
{
    public class SolveController : Controller
    {
        private BugsContext db;
        public SolveController(BugsContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index()
        {
            //var elements = new List<Improvement>(db.Improvements.Include(s => s.Statuses).ToList());
            return View(await db.Improvements.ToListAsync());
        }
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Improvement improvement, string statuses)
        {
            var _imp = improvement;
            //_imp.Statuses.Clear();
            //получаем список всех статусов в БД для сравнения и обновления
            if (!(statuses == null))
            {
                var existingStatuses = db.Statuses.Select(s => s.Name);
                char[] delimiterChars = { ' ', ',', '.', ':', ';' };
                foreach (string ss in statuses.Split(delimiterChars, StringSplitOptions.RemoveEmptyEntries))
                {
                    //если указанный статус в БД уже есть, то связываем задачу и статус
                    if (existingStatuses.Contains(ss))
                    {
                        Status _st = db.Statuses.Single(s => s.Name == ss);
                        _imp.Statuses.Add(_st);
                        //выбрать статус в бд. добавить к задаче. 
                    }
                    //иначе создаем статус, записываем в бд, связываем с задачей.
                    else
                    {
                        Status _st = new Status { Name = ss };
                        db.Statuses.Add(_st);
                        db.SaveChanges();
                        _imp.Statuses.Add(_st);
                        
                        //создать объект статус. добавить в бд. добавить к задаче. обновить бд

                    }

                }
            }
            db.Improvements.Add(_imp);
            
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

BugTracker/Views/Home/Create.cshtml
@model BugTracker.Models.Bug
    @{
        ViewBag.Title = "Добавление бага";

    }
<form asp-action="create" asp-controller="home">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    Статус
    <style>
        select {
            width: 90px; 
            height: 30px
        }
    </style>
    <select id="status" name="Status">
        <option value="New" selected>New</option>
        <option value="In Progress">In Order</option>
        <option value="Done">Done</option>
    </select>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

BugTracker/Views/Home/Delete.cshtml
@model BugTracker.Models.Bug
@{
    ViewBag.Title = "Удаление бага № " + Model.Id.ToString();
}

<div>
    <dl class="dl-horizontal">
        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>Статус</dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>Описание</dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    <div>
        <form asp-controller="Home" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

BugTracker/Views/Home/Edit.cshtml
@model BugTracker.Models.Bug
@{
    ViewBag.Title = "Изменение бага № " + @Model.Id.ToString();
}
<h3>Изменение Бага № @Model.Id.ToString()</h3>
<form asp-action="edit" asp-controller="home" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    <p>
        <style>
            select {
                width: 90px;
                height: 30px
            }
        </style>
        Статус
        @Html.DropDownList("status", new[]
            {
                    new SelectListItem(){ Selected = (Model.Status == "New"), Text = "New", Value = "New"},
                    new SelectListItem(){ Selected = (Model.Status == "In Order"), Text = "In Order", Value = "In Order"},
                    new SelectListItem(){ Selected = (Model.Status == "Done"), Text = "Done", Value = "Done"}
            })
     </p>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>

BugTracker/Views/Home/Index.cshtml
@model IEnumerable<BugTracker.Models.Bug>
@{
    ViewBag.Title = "Все баги";
}
<a asp-action="Create">Добавить баг</a>
<table class="table">
    <tr><td>Id</td><td>Название</td><td>Статус</td><td>Описание</td></tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.Id</td>
    <td>@item.Name</td>
    <td>@item.Status</td>
    <td>@item.Description</td>

    <td>
        <a asp-action="Edit" asp-controller="Home" asp-route-id="@item.Id">Изменить</a> |
        <a asp-action="Delete" asp-controller="Home" asp-route-id="@item.Id">Удалить</a>
    </td> 
</tr>
    }
</table>

BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BugTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Баги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solve" asp-action="Index">Задачи</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BugTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BugTracker/Views/Solve/Create.cshtml
@model BugTracker.Models.Improvement
@{
    ViewBag.Title = "Добавление задачи";

}

<form asp-action="Create" asp-controller="Solve">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="CurrentStatus" class="control-label">Текущий статус</label>
        <input type="text" asp-for="CurrentStatus" value="new" class="form-control" />
    </div>
    <div class="form-group">
        <label name="statuses" class="control-label">Перечислите статусы для данной задачи</label>
        <input type="text" name="statuses" class="form-control" />
    </div>
    <div class="form-group">

    </div>

    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

BugTracker/Views/Solve/Index.cshtml
@model IEnumerable<BugTracker.Models.Improvement>

@{
    ViewBag.Title = "Все задачи";
}
<a asp-action="Create">Добавить задачу</a>
<table class="table">
    <tr><td>Id</td><td>Название</td><td>Статус</td><td>Описание</td></tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.CurrentStatus</td>
            <td>@item.Description</td>

            <td>
                <a asp-action="Edit" asp-controller="Solve" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Solve" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>